name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Replace tokens in B2C policy files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["b2c/policies/*.xml"]'

      - name: Archive B2C policy files
        uses: actions/upload-artifact@v2
        with:
          name: b2c-policies
          path: b2c/policies/*.xml
